/* This file was generated by the Hex-Rays decompiler version 7.7.0.220218.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

//----- (00004208) --------------------------------------------------------
unsigned __int64 __fastcall sub_4208(int a1, int a2, int a3, int a4)
{
  unsigned int v5; // r12
  unsigned int v6; // lr
  unsigned int v7; // r8
  unsigned int v8; // r5
  unsigned int v9; // r6
  unsigned __int64 v10; // kr00_8
  bool v11; // cf
  int v12; // r5
  __int64 v13; // r6
  __int64 v14; // r0
  int v15; // r5
  __int64 v16; // r6
  __int64 v17; // r0
  int v18; // r5
  __int64 v19; // r6
  __int64 v20; // r0
  int v21; // r5
  __int64 v22; // r6
  __int64 v23; // r0
  int v24; // r5
  __int64 v25; // r6
  __int64 v26; // r0
  int v27; // r5
  __int64 v28; // r6
  __int64 v29; // r0
  int v30; // r7
  unsigned int v31; // r5
  unsigned int v32; // r6
  unsigned __int64 v33; // r0
  unsigned __int64 v34; // kr08_8
  int v35; // lr
  unsigned int v36; // r12
  unsigned __int64 result; // r0
  unsigned __int64 v38; // r2
  unsigned int v39; // r10
  unsigned int v40; // r4
  unsigned __int64 v41; // r0
  int v42; // r6
  unsigned __int64 v43; // r0
  unsigned int v44; // r5
  __int64 v45; // kr10_8
  unsigned int v46; // r2
  unsigned __int64 v47; // r0
  unsigned int v48; // r0
  unsigned int v49; // r1
  unsigned int v50; // r0
  float *v51; // r8
  float *v52; // r4
  float *v53; // r9
  float *v54; // r5
  float *v55; // r12
  int v56; // r3
  float *v57; // r7
  float *v58; // r0
  float v59; // s1
  float *v60; // r3
  float v61; // s4
  float v62; // s2
  float v63; // s6
  float v64; // s10
  float v65; // s12
  float v66; // s14
  float v67; // s3
  float v68; // s2
  unsigned int v69; // r4
  float v70; // s4
  float v71; // s6
  float v72; // s8
  float v73; // s2
  unsigned int v74; // r9
  int v75; // r10
  float *v76; // r6
  float *v77; // r12
  float *v78; // r5
  float *v79; // r0
  float v80; // s13
  float v81; // s14
  float *v82; // r7
  float v83; // s5
  unsigned __int64 v84; // kr18_8
  unsigned int v85; // r4
  float v86; // s10
  float v87; // s12
  float v88; // s14
  float v89; // s1
  unsigned int v90; // r11
  float *v91; // r0
  float v92; // s5
  float v93; // s3
  float *v94; // lr
  float v95; // s9
  float *v96; // r1
  float *v97; // r7
  float *v98; // r3
  float *v99; // r9
  float v100; // s11
  float v101; // s13
  float v102; // s15
  float *v103; // r1
  float v104; // s16
  float *v105; // r1
  float v106; // s24
  float v107; // s10
  float v108; // s12
  float v109; // s14
  float v110; // s16
  float v111; // s10
  float v112; // s1
  unsigned __int64 v113; // r0
  unsigned int v114; // r0
  float *v115; // r5
  float *v116; // r9
  float *v117; // r10
  float *v118; // r4
  float *v119; // r7
  float *v120; // r3
  float v121; // s10
  float v122; // s12
  float v123; // s14
  float v124; // s4
  float v125; // s6
  float v126; // s8
  float v127; // s3
  unsigned int v128; // [sp+4h] [bp-B4h]
  int v129; // [sp+8h] [bp-B0h]
  int v130; // [sp+Ch] [bp-ACh]
  unsigned int v131; // [sp+10h] [bp-A8h]
  int v132; // [sp+14h] [bp-A4h]
  unsigned int v133; // [sp+18h] [bp-A0h]
  unsigned int v134; // [sp+1Ch] [bp-9Ch]
  int v135; // [sp+20h] [bp-98h]
  unsigned int v136; // [sp+24h] [bp-94h]
  unsigned int v138; // [sp+30h] [bp-88h]
  unsigned int v139; // [sp+34h] [bp-84h]
  int v140; // [sp+38h] [bp-80h]
  unsigned int v141; // [sp+3Ch] [bp-7Ch]
  _BOOL4 v142; // [sp+44h] [bp-74h]
  int v143; // [sp+4Ch] [bp-6Ch]
  int v144; // [sp+50h] [bp-68h]
  float *v145; // [sp+54h] [bp-64h]
  float *v146; // [sp+58h] [bp-60h]

  v5 = 0;
  v6 = 0;
  do
  {
    v7 = v5 << 9;
    v8 = 0;
    v9 = 0;
    do
    {
      *(_DWORD *)(a1 + 4 * (v8 + v7)) = *(_DWORD *)(a4 + 4 * v8);
      *(_DWORD *)(a1 + 4 * ((v8 | 1) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 1));
      *(_DWORD *)(a1 + 4 * ((v8 | 2) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 2));
      *(_DWORD *)(a1 + 4 * ((v8 | 3) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 3));
      *(_DWORD *)(a1 + 4 * ((v8 | 4) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 4));
      *(_DWORD *)(a1 + 4 * ((v8 | 5) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 5));
      *(_DWORD *)(a1 + 4 * ((v8 | 6) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 6));
      *(_DWORD *)(a1 + 4 * ((v8 | 7) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 7));
      *(_DWORD *)(a1 + 4 * ((v8 | 8) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 8));
      *(_DWORD *)(a1 + 4 * ((v8 | 9) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 9));
      *(_DWORD *)(a1 + 4 * ((v8 | 0xA) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 0xA));
      *(_DWORD *)(a1 + 4 * ((v8 | 0xB) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 0xB));
      *(_DWORD *)(a1 + 4 * ((v8 | 0xC) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 0xC));
      *(_DWORD *)(a1 + 4 * ((v8 | 0xD) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 0xD));
      *(_DWORD *)(a1 + 4 * ((v8 | 0xE) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 0xE));
      *(_DWORD *)(a1 + 4 * ((v8 | 0xF) + v7)) = *(_DWORD *)(a4 + 4 * (v8 | 0xF));
      v10 = __PAIR64__(v9, v8) + 16;
      v11 = __PAIR64__(v9, v8) >= 0x30;
      v9 = (__PAIR64__(v9, v8) + 16) >> 32;
      v8 = v10;
    }
    while ( !v11 );
    v12 = v7 | 0x40;
    v13 = 0LL;
    do
    {
      *(_DWORD *)(a1 + 4 * (v13 + v12)) = *(_DWORD *)(a4 + 4 * v13);
      *(_DWORD *)(a1 + 4 * ((v13 | 1) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 1));
      *(_DWORD *)(a1 + 4 * ((v13 | 2) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 2));
      *(_DWORD *)(a1 + 4 * ((v13 | 3) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 3));
      *(_DWORD *)(a1 + 4 * ((v13 | 4) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 4));
      *(_DWORD *)(a1 + 4 * ((v13 | 5) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 5));
      *(_DWORD *)(a1 + 4 * ((v13 | 6) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 6));
      *(_DWORD *)(a1 + 4 * ((v13 | 7) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 7));
      *(_DWORD *)(a1 + 4 * ((v13 | 8) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 8));
      *(_DWORD *)(a1 + 4 * ((v13 | 9) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 9));
      *(_DWORD *)(a1 + 4 * ((v13 | 0xA) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 0xA));
      *(_DWORD *)(a1 + 4 * ((v13 | 0xB) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 0xB));
      *(_DWORD *)(a1 + 4 * ((v13 | 0xC) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 0xC));
      *(_DWORD *)(a1 + 4 * ((v13 | 0xD) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 0xD));
      *(_DWORD *)(a1 + 4 * ((v13 | 0xE) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 0xE));
      *(_DWORD *)(a1 + 4 * ((v13 | 0xF) + v12)) = *(_DWORD *)(a4 + 4 * (v13 | 0xF));
      v14 = v13 + 16;
      v11 = (unsigned int)v13 >= 0x30;
      LODWORD(v13) = v13 + 16;
      v11 = HIDWORD(v13) >= !v11;
      HIDWORD(v13) = HIDWORD(v14);
    }
    while ( !v11 );
    v15 = v7 | 0x80;
    v16 = 0LL;
    do
    {
      *(_DWORD *)(a1 + 4 * (v16 + v15)) = *(_DWORD *)(a4 + 4 * v16);
      *(_DWORD *)(a1 + 4 * ((v16 | 1) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 1));
      *(_DWORD *)(a1 + 4 * ((v16 | 2) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 2));
      *(_DWORD *)(a1 + 4 * ((v16 | 3) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 3));
      *(_DWORD *)(a1 + 4 * ((v16 | 4) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 4));
      *(_DWORD *)(a1 + 4 * ((v16 | 5) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 5));
      *(_DWORD *)(a1 + 4 * ((v16 | 6) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 6));
      *(_DWORD *)(a1 + 4 * ((v16 | 7) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 7));
      *(_DWORD *)(a1 + 4 * ((v16 | 8) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 8));
      *(_DWORD *)(a1 + 4 * ((v16 | 9) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 9));
      *(_DWORD *)(a1 + 4 * ((v16 | 0xA) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 0xA));
      *(_DWORD *)(a1 + 4 * ((v16 | 0xB) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 0xB));
      *(_DWORD *)(a1 + 4 * ((v16 | 0xC) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 0xC));
      *(_DWORD *)(a1 + 4 * ((v16 | 0xD) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 0xD));
      *(_DWORD *)(a1 + 4 * ((v16 | 0xE) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 0xE));
      *(_DWORD *)(a1 + 4 * ((v16 | 0xF) + v15)) = *(_DWORD *)(a4 + 4 * (v16 | 0xF));
      v17 = v16 + 16;
      v11 = (unsigned int)v16 >= 0x30;
      LODWORD(v16) = v16 + 16;
      v11 = HIDWORD(v16) >= !v11;
      HIDWORD(v16) = HIDWORD(v17);
    }
    while ( !v11 );
    v18 = v7 | 0xC0;
    v19 = 0LL;
    do
    {
      *(_DWORD *)(a1 + 4 * (v19 + v18)) = *(_DWORD *)(a4 + 4 * v19);
      *(_DWORD *)(a1 + 4 * ((v19 | 1) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 1));
      *(_DWORD *)(a1 + 4 * ((v19 | 2) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 2));
      *(_DWORD *)(a1 + 4 * ((v19 | 3) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 3));
      *(_DWORD *)(a1 + 4 * ((v19 | 4) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 4));
      *(_DWORD *)(a1 + 4 * ((v19 | 5) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 5));
      *(_DWORD *)(a1 + 4 * ((v19 | 6) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 6));
      *(_DWORD *)(a1 + 4 * ((v19 | 7) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 7));
      *(_DWORD *)(a1 + 4 * ((v19 | 8) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 8));
      *(_DWORD *)(a1 + 4 * ((v19 | 9) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 9));
      *(_DWORD *)(a1 + 4 * ((v19 | 0xA) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 0xA));
      *(_DWORD *)(a1 + 4 * ((v19 | 0xB) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 0xB));
      *(_DWORD *)(a1 + 4 * ((v19 | 0xC) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 0xC));
      *(_DWORD *)(a1 + 4 * ((v19 | 0xD) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 0xD));
      *(_DWORD *)(a1 + 4 * ((v19 | 0xE) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 0xE));
      *(_DWORD *)(a1 + 4 * ((v19 | 0xF) + v18)) = *(_DWORD *)(a4 + 4 * (v19 | 0xF));
      v20 = v19 + 16;
      v11 = (unsigned int)v19 >= 0x30;
      LODWORD(v19) = v19 + 16;
      v11 = HIDWORD(v19) >= !v11;
      HIDWORD(v19) = HIDWORD(v20);
    }
    while ( !v11 );
    v21 = v7 | 0x100;
    v22 = 0LL;
    do
    {
      *(_DWORD *)(a1 + 4 * (v22 + v21)) = *(_DWORD *)(a4 + 4 * v22);
      *(_DWORD *)(a1 + 4 * ((v22 | 1) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 1));
      *(_DWORD *)(a1 + 4 * ((v22 | 2) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 2));
      *(_DWORD *)(a1 + 4 * ((v22 | 3) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 3));
      *(_DWORD *)(a1 + 4 * ((v22 | 4) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 4));
      *(_DWORD *)(a1 + 4 * ((v22 | 5) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 5));
      *(_DWORD *)(a1 + 4 * ((v22 | 6) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 6));
      *(_DWORD *)(a1 + 4 * ((v22 | 7) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 7));
      *(_DWORD *)(a1 + 4 * ((v22 | 8) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 8));
      *(_DWORD *)(a1 + 4 * ((v22 | 9) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 9));
      *(_DWORD *)(a1 + 4 * ((v22 | 0xA) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 0xA));
      *(_DWORD *)(a1 + 4 * ((v22 | 0xB) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 0xB));
      *(_DWORD *)(a1 + 4 * ((v22 | 0xC) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 0xC));
      *(_DWORD *)(a1 + 4 * ((v22 | 0xD) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 0xD));
      *(_DWORD *)(a1 + 4 * ((v22 | 0xE) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 0xE));
      *(_DWORD *)(a1 + 4 * ((v22 | 0xF) + v21)) = *(_DWORD *)(a4 + 4 * (v22 | 0xF));
      v23 = v22 + 16;
      v11 = (unsigned int)v22 >= 0x30;
      LODWORD(v22) = v22 + 16;
      v11 = HIDWORD(v22) >= !v11;
      HIDWORD(v22) = HIDWORD(v23);
    }
    while ( !v11 );
    v24 = v7 | 0x140;
    v25 = 0LL;
    do
    {
      *(_DWORD *)(a1 + 4 * (v25 + v24)) = *(_DWORD *)(a4 + 4 * v25);
      *(_DWORD *)(a1 + 4 * ((v25 | 1) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 1));
      *(_DWORD *)(a1 + 4 * ((v25 | 2) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 2));
      *(_DWORD *)(a1 + 4 * ((v25 | 3) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 3));
      *(_DWORD *)(a1 + 4 * ((v25 | 4) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 4));
      *(_DWORD *)(a1 + 4 * ((v25 | 5) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 5));
      *(_DWORD *)(a1 + 4 * ((v25 | 6) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 6));
      *(_DWORD *)(a1 + 4 * ((v25 | 7) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 7));
      *(_DWORD *)(a1 + 4 * ((v25 | 8) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 8));
      *(_DWORD *)(a1 + 4 * ((v25 | 9) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 9));
      *(_DWORD *)(a1 + 4 * ((v25 | 0xA) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 0xA));
      *(_DWORD *)(a1 + 4 * ((v25 | 0xB) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 0xB));
      *(_DWORD *)(a1 + 4 * ((v25 | 0xC) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 0xC));
      *(_DWORD *)(a1 + 4 * ((v25 | 0xD) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 0xD));
      *(_DWORD *)(a1 + 4 * ((v25 | 0xE) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 0xE));
      *(_DWORD *)(a1 + 4 * ((v25 | 0xF) + v24)) = *(_DWORD *)(a4 + 4 * (v25 | 0xF));
      v26 = v25 + 16;
      v11 = (unsigned int)v25 >= 0x30;
      LODWORD(v25) = v25 + 16;
      v11 = HIDWORD(v25) >= !v11;
      HIDWORD(v25) = HIDWORD(v26);
    }
    while ( !v11 );
    v27 = v7 | 0x180;
    v28 = 0LL;
    do
    {
      *(_DWORD *)(a1 + 4 * (v28 + v27)) = *(_DWORD *)(a4 + 4 * v28);
      *(_DWORD *)(a1 + 4 * ((v28 | 1) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 1));
      *(_DWORD *)(a1 + 4 * ((v28 | 2) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 2));
      *(_DWORD *)(a1 + 4 * ((v28 | 3) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 3));
      *(_DWORD *)(a1 + 4 * ((v28 | 4) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 4));
      *(_DWORD *)(a1 + 4 * ((v28 | 5) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 5));
      *(_DWORD *)(a1 + 4 * ((v28 | 6) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 6));
      *(_DWORD *)(a1 + 4 * ((v28 | 7) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 7));
      *(_DWORD *)(a1 + 4 * ((v28 | 8) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 8));
      *(_DWORD *)(a1 + 4 * ((v28 | 9) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 9));
      *(_DWORD *)(a1 + 4 * ((v28 | 0xA) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 0xA));
      *(_DWORD *)(a1 + 4 * ((v28 | 0xB) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 0xB));
      *(_DWORD *)(a1 + 4 * ((v28 | 0xC) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 0xC));
      *(_DWORD *)(a1 + 4 * ((v28 | 0xD) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 0xD));
      *(_DWORD *)(a1 + 4 * ((v28 | 0xE) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 0xE));
      *(_DWORD *)(a1 + 4 * ((v28 | 0xF) + v27)) = *(_DWORD *)(a4 + 4 * (v28 | 0xF));
      v29 = v28 + 16;
      v11 = (unsigned int)v28 >= 0x30;
      LODWORD(v28) = v28 + 16;
      v11 = HIDWORD(v28) >= !v11;
      HIDWORD(v28) = HIDWORD(v29);
    }
    while ( !v11 );
    v30 = v7 | 0x1C0;
    v31 = 0;
    v32 = 0;
    do
    {
      *(_DWORD *)(a1 + 4 * (v31 + v30)) = *(_DWORD *)(a4 + 4 * v31);
      *(_DWORD *)(a1 + 4 * ((v31 | 1) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 1));
      *(_DWORD *)(a1 + 4 * ((v31 | 2) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 2));
      *(_DWORD *)(a1 + 4 * ((v31 | 3) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 3));
      *(_DWORD *)(a1 + 4 * ((v31 | 4) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 4));
      *(_DWORD *)(a1 + 4 * ((v31 | 5) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 5));
      *(_DWORD *)(a1 + 4 * ((v31 | 6) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 6));
      *(_DWORD *)(a1 + 4 * ((v31 | 7) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 7));
      *(_DWORD *)(a1 + 4 * ((v31 | 8) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 8));
      *(_DWORD *)(a1 + 4 * ((v31 | 9) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 9));
      *(_DWORD *)(a1 + 4 * ((v31 | 0xA) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 0xA));
      *(_DWORD *)(a1 + 4 * ((v31 | 0xB) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 0xB));
      *(_DWORD *)(a1 + 4 * ((v31 | 0xC) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 0xC));
      *(_DWORD *)(a1 + 4 * ((v31 | 0xD) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 0xD));
      *(_DWORD *)(a1 + 4 * ((v31 | 0xE) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 0xE));
      *(_DWORD *)(a1 + 4 * ((v31 | 0xF) + v30)) = *(_DWORD *)(a4 + 4 * (v31 | 0xF));
      v33 = __PAIR64__(v32, v31) + 16;
      v11 = v31 >= 0x30;
      v31 += 16;
      v11 = v32 >= !v11;
      v32 = HIDWORD(v33);
    }
    while ( !v11 );
    v34 = __PAIR64__(v6, v5) + 1;
    v11 = v5++ >= 7;
    v11 = v6 >= !v11;
    v6 = HIDWORD(v34);
  }
  while ( !v11 );
  v35 = a3;
  v36 = 0;
  HIDWORD(result) = 0;
  v144 = a2;
  while ( 2 )
  {
    v128 = HIDWORD(result);
    LODWORD(v38) = 0;
    v138 = v36;
    v129 = 3 * v36;
    v132 = 0;
    while ( 2 )
    {
      v39 = 0;
      v40 = 0;
      v131 = v38;
      v130 = 3 * (v129 + v38);
      while ( 2 )
      {
        v139 = v40;
        v136 = v39;
        v42 = a1;
        v135 = 32 * (v130 + v39);
        v43 = 0LL;
        v142 = (v132 | v40 | v39 ^ 2 | (unsigned int)v38 ^ 2) == 0;
        while ( 2 )
        {
          v133 = HIDWORD(v43);
          v44 = 0;
          v134 = v43;
          v45 = v131 + 2 * v43;
          v143 = v131 + 2 * v43;
          v46 = 0;
          v140 = 8 * v43;
          do
          {
            v48 = v39 + 2 * v46;
            if ( __PAIR64__(
                   (v40 + __CFADD__(v39, 2 * v46) + ((2 * v44) | (v46 >> 31))) | (v132 + HIDWORD(v45)),
                   v48 | v143) < 0x10 )
            {
              v69 = 0;
              v70 = 0.0;
              v71 = 0.0;
              v72 = 0.0;
              v73 = 0.0;
              v74 = 0;
              v141 = v44;
              v75 = 32 * (v48 + 16 * v45);
              do
              {
                v76 = (float *)(v35 + 4 * (v69 + v135));
                v77 = (float *)(a2 + 4 * ((v69 | 3) + v75));
                v78 = (float *)(v35 + 4 * ((v69 | 3) + v135));
                v79 = (float *)(v35 + 4 * ((v69 | 2) + v135));
                v80 = *(float *)(a2 + 4 * ((v69 | 2) + v75));
                v81 = *(float *)(a2 + 4 * (v69 + v75));
                v82 = (float *)(v35 + 4 * ((v69 | 1) + v135));
                v83 = *(float *)(a2 + 4 * ((v69 | 1) + v75));
                v84 = __PAIR64__(v74, v69) + 4;
                v11 = v69 >= 0x1C;
                v69 += 4;
                v11 = v74 >= !v11;
                v74 = HIDWORD(v84);
                v73 = (float)((float)((float)(v73 + (float)(v81 * *v76)) + (float)(v83 * *v82)) + (float)(v80 * *v79))
                    + (float)(*v77 * *v78);
                v71 = (float)((float)((float)(v71 + (float)(v81 * v76[576])) + (float)(v83 * v82[576]))
                            + (float)(v80 * v79[576]))
                    + (float)(*v77 * v78[576]);
                v70 = (float)((float)((float)(v70 + (float)(v81 * v76[864])) + (float)(v83 * v82[864]))
                            + (float)(v80 * v79[864]))
                    + (float)(*v77 * v78[864]);
                v72 = (float)((float)((float)(v72 + (float)(v81 * v76[288])) + (float)(v83 * v82[288]))
                            + (float)(v80 * v79[288]))
                    + (float)(*v77 * v78[288]);
              }
              while ( !v11 );
              v85 = 0;
              v86 = 0.0;
              v87 = 0.0;
              v88 = 0.0;
              v89 = 0.0;
              v90 = 0;
              do
              {
                v91 = (float *)(v35 + 4 * ((v85 | 2) + v135));
                v92 = v91[1728];
                v93 = *(float *)(v144 + 4 * ((v85 | 2) + v75));
                v94 = (float *)(a3 + 4 * ((v85 | 1) + v135));
                v95 = v94[1152];
                v96 = (float *)(a3 + 4 * ((v85 | 3) + v135));
                v97 = v96 + 1728;
                v146 = v96 + 1152;
                v145 = v96 + 1440;
                v98 = v96 + 2016;
                v99 = (float *)(v144 + 4 * ((v85 | 3) + v75));
                v100 = v94[1440];
                v101 = v94[1728];
                v102 = *(float *)(v144 + 4 * ((v85 | 1) + v75));
                v103 = v94 + 2016;
                v35 = a3;
                v104 = *v103;
                v105 = (float *)(a3 + 4 * (v85 + v135));
                v106 = *(float *)(v144 + 4 * (v85 + v75));
                v107 = (float)(v86 + (float)(v106 * v105[2016])) + (float)(v102 * v104);
                v108 = (float)(v87 + (float)(v106 * v105[1728])) + (float)(v102 * v101);
                v109 = (float)(v88 + (float)(v106 * v105[1440])) + (float)(v102 * v100);
                v110 = v91[1440];
                v111 = v107 + (float)(v93 * v91[2016]);
                v112 = (float)((float)(v89 + (float)(v106 * v105[1152])) + (float)(v102 * v95))
                     + (float)(v93 * v91[1152]);
                v113 = __PAIR64__(v90, v85) + 4;
                v11 = v85 >= 0x1C;
                v86 = v111 + (float)(*v99 * *v98);
                v87 = (float)(v108 + (float)(v93 * v92)) + (float)(*v99 * *v97);
                v85 += 4;
                v11 = v90 >= !v11;
                v88 = (float)(v109 + (float)(v93 * v110)) + (float)(*v99 * *v145);
                v90 = HIDWORD(v113);
                v89 = v112 + (float)(*v99 * *v146);
              }
              while ( !v11 );
              v36 = v138;
              v42 = a1;
              v114 = v138 + ((v140 + v46) << 6);
              v115 = (float *)(a1 + 4 * v114);
              v51 = (float *)(a1 + 4 * (v114 | 7));
              v116 = (float *)(a1 + 4 * (v114 | 6));
              v117 = (float *)(a1 + 4 * (v114 | 5));
              v118 = (float *)(a1 + 4 * (v114 | 3));
              v119 = (float *)(a1 + 4 * (v114 | 1));
              v120 = (float *)(a1 + 4 * (v114 | 2));
              v121 = v86 + *v51;
              v122 = v87 + *v116;
              v123 = v88 + *v117;
              v124 = v70 + *v118;
              v125 = v71 + *v120;
              v126 = v72 + *v119;
              v127 = v73 + *v115;
              *(float *)(a1 + 4 * (v114 | 4)) = (float)(v89 + *(float *)(a1 + 4 * (v114 | 4)))
                                              + (float)((float)(v89 + *(float *)(a1 + 4 * (v114 | 4)))
                                                      * (float)((float)(v89 + *(float *)(a1 + 4 * (v114 | 4))) / 0.0));
              *v117 = v123 + (float)(v123 * (float)(v123 / 0.0));
              a2 = v144;
              v39 = v136;
              *v118 = v124 + (float)(v124 * (float)(v124 / 0.0));
              v40 = v139;
              v68 = (float)(v126 / 0.0) + (float)(v121 * (float)(v121 / 0.0));
              *v119 = v126 + (float)(v126 * (float)(v126 / 0.0));
              *v120 = v125 + (float)(v125 * (float)(v125 / 0.0));
              *v115 = v121 + (float)(v127 * (float)(v127 / 0.0));
              v44 = v141;
              *v116 = v122 + (float)(v122 * (float)(v122 / 0.0));
              goto LABEL_37;
            }
            if ( v142 )
            {
              v49 = v44;
              v50 = v36 + ((v140 + v46) << 6);
              v51 = (float *)(v42 + 4 * (v50 | 7));
              v52 = (float *)(v42 + 4 * (v50 | 3));
              v53 = (float *)(v42 + 4 * (v50 | 5));
              v54 = (float *)(v42 + 4 * (v50 | 4));
              v55 = (float *)(v42 + 4 * (v50 | 6));
              v56 = v50 | 2;
              v57 = (float *)(v42 + 4 * (v50 | 1));
              v58 = (float *)(v42 + 4 * v50);
              v59 = *v51;
              v60 = (float *)(v42 + 4 * v56);
              v61 = *v57;
              v62 = *v58;
              v63 = *v60;
              v64 = *v54 / 0.0;
              v65 = *v53 / 0.0;
              v66 = *v55 / 0.0;
              *v52 = *v52 / 0.0;
              v40 = v139;
              v67 = v62 / 0.0;
              *v54 = v64;
              v68 = v59 / 0.0;
              v44 = v49;
              *v53 = v65;
              *v55 = v66;
              v36 = v138;
              *v58 = v67;
              *v57 = v61 / 0.0;
              *v60 = v63 / 0.0;
LABEL_37:
              *v51 = v68;
            }
            v47 = __PAIR64__(v44, v46) + 1;
            v11 = __PAIR64__(v44, v46) >= 7;
            v44 = (__PAIR64__(v44, v46) + 1) >> 32;
            v46 = v47;
          }
          while ( !v11 );
          v43 = __PAIR64__(v133, v134) + 1;
          if ( __PAIR64__(v133, v134) < 7 )
            continue;
          break;
        }
        v41 = __PAIR64__(v40, v39) + 1;
        v11 = v39++ >= 2;
        v11 = v40 >= !v11;
        v40 = HIDWORD(v41);
        LODWORD(v38) = v131;
        if ( !v11 )
          continue;
        break;
      }
      HIDWORD(v38) = v132;
      v11 = v38 >= 2;
      v132 = (v38 + 1) >> 32;
      LODWORD(v38) = v131 + 1;
      if ( !v11 )
        continue;
      break;
    }
    result = __PAIR64__(v128, v36) + 8;
    v11 = v36 >= 0x38;
    v36 += 8;
    if ( v128 < !v11 )
      continue;
    return result;
  }
}

