/* This file was generated by the Hex-Rays decompiler version 7.7.0.220218.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

//----- (0000000000001483) ----------------------------------------------------
__int64 __fastcall sub_1483(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5)
{
  int v5; // xmm0_4
  int i; // [rsp+34h] [rbp-34h]
  int j; // [rsp+38h] [rbp-30h]
  int k; // [rsp+3Ch] [rbp-2Ch]
  int m; // [rsp+40h] [rbp-28h]
  int n; // [rsp+44h] [rbp-24h]
  int ii; // [rsp+48h] [rbp-20h]
  int jj; // [rsp+4Ch] [rbp-1Ch]
  int kk; // [rsp+50h] [rbp-18h]
  int mm; // [rsp+54h] [rbp-14h]
  __int64 v16; // [rsp+58h] [rbp-10h]
  __int64 v17; // [rsp+60h] [rbp-8h]

  v16 = a5 + 233792;
  for ( i = 0; i <= 9; ++i )
  {
    for ( j = 0; j <= 9; ++j )
    {
      for ( k = 0; k <= 63; ++k )
      {
        if ( i <= 0 || i > 8 || j <= 0 || j > 8 )
          v5 = 0;
        else
          v5 = *(_DWORD *)(4LL * (((8 * i + j) << 6) + k) - 2304 + a1);
        *(_DWORD *)(4LL * (((10 * i + j) << 6) + k) + v16) = v5;
      }
    }
  }
  for ( m = 0; m <= 63; ++m )
  {
    v17 = a5 + 278976;
    for ( n = 0; n <= 63; ++n )
    {
      *(_DWORD *)(4LL * n + v17) = 0;
      for ( ii = 0; ii <= 2; ++ii )
      {
        for ( jj = 0; jj <= 2; ++jj )
        {
          for ( kk = 0; kk <= 63; ++kk )
            *(float *)(4LL * n + v17) = (float)(*(float *)(4LL * (((((3 * ii + jj) << 6) + kk) << 6) + n) + a2)
                                              * *(float *)(4LL * (((jj + 10 * (ii + (m >> 3)) + (m & 7)) << 6) + kk)
                                                         + v16))
                                      + *(float *)(4LL * n + v17);
        }
      }
    }
    for ( mm = 0; mm <= 63; ++mm )
      *(float *)(4LL * ((m << 6) + mm) + a4) = *(float *)(4LL * mm + a3) + *(float *)(4LL * mm + v17);
  }
  return 0LL;
}

