/* This file was generated by the Hex-Rays decompiler version 7.7.0.220218.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

//----- (00005238) --------------------------------------------------------
int32_t __fastcall sub_5238(void *arg0, void *arg1, void *arg2, void *arg3)
{
  char *v6; // r0
  int v7; // r2
  char *v8; // r4
  int v9; // r1
  char *v10; // r3
  int v11; // r7
  int v12; // r5
  char *v13; // r12
  char *v14; // r9
  int i; // r1
  float *v16; // r12
  float *v17; // r7
  int j; // r5
  int v19; // r2
  float v20; // s15
  int v21; // lr
  int v22; // r4
  float *v23; // r3
  int v24; // r10
  float v25; // s12
  float *v26; // r8
  float *v27; // r9
  float *v28; // r3
  float *v29; // r2
  float v30; // s13
  float v31; // s15
  float Conv2dOutput[64]; // [sp+20h] [bp-128h] BYREF

  if ( !v6 )
    return -1;
  v7 = 0;
  v8 = (char *)arg0 - 2304;
  do
  {
    v9 = 0;
    v10 = &v6[2560 * v7];
    v11 = v7 << 9;
    do
    {
      v13 = &v8[4 * v11];
      v14 = v10 + 256;
      do
      {
        if ( (unsigned int)(v7 - 1) > 7 || !v9 || v9 == 9 )
          v12 = 0;
        else
          v12 = *(_DWORD *)v13;
        *(_DWORD *)v10 = v12;
        v10 += 4;
        v13 += 4;
      }
      while ( v10 != v14 );
      ++v9;
      v11 += 64;
    }
    while ( v9 != 10 );
    ++v7;
  }
  while ( v7 != 10 );
  for ( i = 0; i != 64; ++i )
  {
    v16 = Conv2dOutput;
    v17 = Conv2dOutput;
    for ( j = 0; j != 64; ++j )
    {
      *v17++ = 0.0;
      v19 = 0;
      v20 = 0.0;
      v21 = (i & 7) + 10 * (i >> 3);
      do
      {
        v22 = v19 << 6;
        v23 = (float *)&v6[256 * v21];
        v19 += 3;
        v24 = v22 + 192;
        while ( 1 )
        {
          v26 = (float *)((char *)arg1 + 256 * v22 + 4 * j);
          v27 = v23 + 64;
          do
          {
            v25 = *v23++;
            v20 = v20 + (float)(v25 * *v26);
            v26 += 64;
          }
          while ( v27 != v23 );
          v22 += 64;
          if ( v24 == v22 )
            break;
          v23 = v27;
        }
        v21 += 10;
      }
      while ( v19 != 9 );
      *(v17 - 1) = v20;
    }
    v28 = (float *)arg2;
    v29 = (float *)((char *)arg3 + 256 * i);
    do
    {
      v30 = *v28++;
      v31 = *v16++;
      *v29++ = v31 + v30;
    }
    while ( (char *)arg2 + 256 != (char *)v28 );
  }
}

