/* This file was generated by the Hex-Rays decompiler version 7.7.0.220218.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

//----- (000055A0) --------------------------------------------------------
__int64 __fastcall sub_55A0(__int64 a1, __int64 a2, __int64 a3, _OWORD *a4)
{
  _OWORD *v6; // r8
  __int64 v7; // r9
  __int64 v8; // rax
  __int64 v9; // r10
  __int64 v10; // r11
  _OWORD *v11; // rdx
  __int64 v12; // rsi
  _OWORD *v13; // rsi
  __int64 v14; // rdx
  _OWORD *v15; // rdx
  __int64 v16; // rsi
  _OWORD *v17; // rsi
  __int64 v18; // rdx
  _OWORD *v19; // rdx
  __int64 v20; // rsi
  _OWORD *v21; // rsi
  __int64 v22; // rdx
  _OWORD *v23; // rdx
  __int64 v24; // rsi
  __int64 v25; // rdx
  __int64 v26; // r14
  __int64 v27; // r12
  __int64 v28; // rbp
  __int64 v29; // rcx
  __int64 result; // rax
  __int64 v31; // r13
  __int64 v32; // rcx
  __int64 v33; // r15
  unsigned __int64 v34; // r10
  __int64 v35; // rax
  unsigned __int64 v36; // rdx
  __int64 v37; // r8
  unsigned int v38; // r9d
  __int64 v39; // rcx
  unsigned __int64 v40; // r11
  __int64 v41; // r14
  __m128 v42; // xmm3
  __m128 v43; // xmm4
  __m128 v44; // xmm5
  __m128 v45; // xmm6
  __m128 v46; // xmm7
  __m128 v47; // xmm8
  __m128 v48; // xmm9
  __m128 v49; // xmm10
  __m128 v50; // xmm11
  __m128 v51; // xmm2
  __m128 v52; // xmm0
  __m128 v53; // xmm13
  __m128 v54; // xmm12
  __m128 v55; // xmm14
  __m128 v56; // xmm15
  __m128 v57; // xmm1
  __m128 v58; // xmm0
  __m128 v59; // xmm0
  unsigned __int64 v60; // rax
  __int64 v61; // rsi
  __int64 v62; // rsi
  __int64 v63; // rsi
  __int64 v64; // rsi
  __int64 v65; // rax
  bool v66; // cf
  __int64 v67; // rcx
  unsigned __int64 v68; // rdx
  unsigned int v69; // ebp
  __int64 v70; // rax
  unsigned __int64 v71; // rbx
  __m128 v72; // xmm0
  __int64 v73; // rsi
  __m128 v74; // xmm1
  __m128 v75; // xmm2
  __m128 v76; // xmm3
  __m128 v77; // xmm4
  unsigned __int64 v78; // rsi
  __m128 v79; // xmm2
  __int64 v80; // rsi
  __m128 v81; // xmm1
  __int64 v82; // [rsp+0h] [rbp-140h]
  __int64 v83; // [rsp+8h] [rbp-138h]
  __int64 v84; // [rsp+10h] [rbp-130h]
  __m128 v85; // [rsp+18h] [rbp-128h]
  __m128 v86; // [rsp+28h] [rbp-118h]
  __m128 v87; // [rsp+38h] [rbp-108h]
  __m128 v88; // [rsp+48h] [rbp-F8h]
  __m128 v89; // [rsp+58h] [rbp-E8h]
  __m128 v90; // [rsp+68h] [rbp-D8h]
  __m128 v91; // [rsp+78h] [rbp-C8h]
  __m128 v92; // [rsp+88h] [rbp-B8h]
  __m128 v93; // [rsp+98h] [rbp-A8h]
  __m128 v94; // [rsp+A8h] [rbp-98h]
  __m128 v95; // [rsp+B8h] [rbp-88h]
  __int64 v96; // [rsp+D0h] [rbp-70h]
  __int64 v97; // [rsp+D8h] [rbp-68h]
  __int64 v98; // [rsp+E0h] [rbp-60h]
  __int64 v99; // [rsp+E8h] [rbp-58h]
  __int64 v100; // [rsp+F0h] [rbp-50h]
  __int64 v101; // [rsp+F8h] [rbp-48h]
  __int64 v102; // [rsp+100h] [rbp-40h]
  __int64 v103; // [rsp+108h] [rbp-38h]

  v6 = a4 + 16;
  v7 = 0LL;
  v8 = a1;
  do
  {
    v10 = v7 << 11;
    v11 = (_OWORD *)(a1 + (v7 << 11) + 256);
    if ( a1 + (v7 << 11) >= (unsigned __int64)v6 || v11 <= a4 )
    {
      *(_OWORD *)(a1 + (v7 << 11)) = *a4;
      *(_OWORD *)(a1 + ((v7 << 11) | 0x10)) = a4[1];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x20)) = a4[2];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x30)) = a4[3];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x40)) = a4[4];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x50)) = a4[5];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x60)) = a4[6];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x70)) = a4[7];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x80)) = a4[8];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x90)) = a4[9];
      *(_OWORD *)(a1 + ((v7 << 11) | 0xA0)) = a4[10];
      *(_OWORD *)(a1 + ((v7 << 11) | 0xB0)) = a4[11];
      *(_OWORD *)(a1 + ((v7 << 11) | 0xC0)) = a4[12];
      *(_OWORD *)(a1 + ((v7 << 11) | 0xD0)) = a4[13];
      *(_OWORD *)(a1 + ((v7 << 11) | 0xE0)) = a4[14];
      *(_OWORD *)(a1 + ((v7 << 11) | 0xF0)) = a4[15];
    }
    else
    {
      v12 = -64LL;
      do
      {
        *(_DWORD *)(v8 + 4 * v12 + 256) = *((_DWORD *)a4 + v12 + 64);
        ++v12;
      }
      while ( v12 );
    }
    v13 = (_OWORD *)(a1 + v10 + 512);
    if ( v11 >= v6 || v13 <= a4 )
    {
      *v11 = *a4;
      *(_OWORD *)(a1 + ((v7 << 11) | 0x110)) = a4[1];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x120)) = a4[2];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x130)) = a4[3];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x140)) = a4[4];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x150)) = a4[5];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x160)) = a4[6];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x170)) = a4[7];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x180)) = a4[8];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x190)) = a4[9];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x1A0)) = a4[10];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x1B0)) = a4[11];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x1C0)) = a4[12];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x1D0)) = a4[13];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x1E0)) = a4[14];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x1F0)) = a4[15];
    }
    else
    {
      v14 = -64LL;
      do
      {
        *(_DWORD *)(v8 + 4 * v14 + 512) = *((_DWORD *)a4 + v14 + 64);
        ++v14;
      }
      while ( v14 );
    }
    v15 = (_OWORD *)(a1 + v10 + 768);
    if ( v13 >= v6 || v15 <= a4 )
    {
      *v13 = *a4;
      *(_OWORD *)(a1 + ((v7 << 11) | 0x210)) = a4[1];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x220)) = a4[2];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x230)) = a4[3];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x240)) = a4[4];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x250)) = a4[5];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x260)) = a4[6];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x270)) = a4[7];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x280)) = a4[8];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x290)) = a4[9];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x2A0)) = a4[10];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x2B0)) = a4[11];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x2C0)) = a4[12];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x2D0)) = a4[13];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x2E0)) = a4[14];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x2F0)) = a4[15];
    }
    else
    {
      v16 = -64LL;
      do
      {
        *(_DWORD *)(v8 + 4 * v16 + 768) = *((_DWORD *)a4 + v16 + 64);
        ++v16;
      }
      while ( v16 );
    }
    v17 = (_OWORD *)(a1 + v10 + 1024);
    if ( v15 >= v6 || v17 <= a4 )
    {
      *v15 = *a4;
      *(_OWORD *)(a1 + ((v7 << 11) | 0x310)) = a4[1];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x320)) = a4[2];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x330)) = a4[3];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x340)) = a4[4];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x350)) = a4[5];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x360)) = a4[6];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x370)) = a4[7];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x380)) = a4[8];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x390)) = a4[9];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x3A0)) = a4[10];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x3B0)) = a4[11];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x3C0)) = a4[12];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x3D0)) = a4[13];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x3E0)) = a4[14];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x3F0)) = a4[15];
    }
    else
    {
      v18 = -64LL;
      do
      {
        *(_DWORD *)(v8 + 4 * v18 + 1024) = *((_DWORD *)a4 + v18 + 64);
        ++v18;
      }
      while ( v18 );
    }
    v19 = (_OWORD *)(a1 + v10 + 1280);
    if ( v17 >= v6 || v19 <= a4 )
    {
      *v17 = *a4;
      *(_OWORD *)(a1 + ((v7 << 11) | 0x410)) = a4[1];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x420)) = a4[2];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x430)) = a4[3];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x440)) = a4[4];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x450)) = a4[5];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x460)) = a4[6];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x470)) = a4[7];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x480)) = a4[8];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x490)) = a4[9];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x4A0)) = a4[10];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x4B0)) = a4[11];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x4C0)) = a4[12];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x4D0)) = a4[13];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x4E0)) = a4[14];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x4F0)) = a4[15];
    }
    else
    {
      v20 = -64LL;
      do
      {
        *(_DWORD *)(v8 + 4 * v20 + 1280) = *((_DWORD *)a4 + v20 + 64);
        ++v20;
      }
      while ( v20 );
    }
    v21 = (_OWORD *)(a1 + v10 + 1536);
    if ( v19 >= v6 || v21 <= a4 )
    {
      *v19 = *a4;
      *(_OWORD *)(a1 + ((v7 << 11) | 0x510)) = a4[1];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x520)) = a4[2];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x530)) = a4[3];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x540)) = a4[4];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x550)) = a4[5];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x560)) = a4[6];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x570)) = a4[7];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x580)) = a4[8];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x590)) = a4[9];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x5A0)) = a4[10];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x5B0)) = a4[11];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x5C0)) = a4[12];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x5D0)) = a4[13];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x5E0)) = a4[14];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x5F0)) = a4[15];
    }
    else
    {
      v22 = -64LL;
      do
      {
        *(_DWORD *)(v8 + 4 * v22 + 1536) = *((_DWORD *)a4 + v22 + 64);
        ++v22;
      }
      while ( v22 );
    }
    v23 = (_OWORD *)(a1 + v10 + 1792);
    if ( v21 >= v6 || v23 <= a4 )
    {
      *v21 = *a4;
      *(_OWORD *)(a1 + ((v7 << 11) | 0x610)) = a4[1];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x620)) = a4[2];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x630)) = a4[3];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x640)) = a4[4];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x650)) = a4[5];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x660)) = a4[6];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x670)) = a4[7];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x680)) = a4[8];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x690)) = a4[9];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x6A0)) = a4[10];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x6B0)) = a4[11];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x6C0)) = a4[12];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x6D0)) = a4[13];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x6E0)) = a4[14];
      *(_OWORD *)(a1 + ((v7 << 11) | 0x6F0)) = a4[15];
      if ( v23 >= v6 )
        goto LABEL_2;
    }
    else
    {
      v24 = -64LL;
      do
      {
        *(_DWORD *)(v8 + 4 * v24 + 1792) = *((_DWORD *)a4 + v24 + 64);
        ++v24;
      }
      while ( v24 );
      if ( v23 >= v6 )
      {
LABEL_2:
        *v23 = *a4;
        v9 = v7 << 11;
        *(_OWORD *)(a1 + (v9 | 0x710)) = a4[1];
        *(_OWORD *)(a1 + (v9 | 0x720)) = a4[2];
        *(_OWORD *)(a1 + (v9 | 0x730)) = a4[3];
        *(_OWORD *)(a1 + (v9 | 0x740)) = a4[4];
        *(_OWORD *)(a1 + (v9 | 0x750)) = a4[5];
        *(_OWORD *)(a1 + (v9 | 0x760)) = a4[6];
        *(_OWORD *)(a1 + (v9 | 0x770)) = a4[7];
        *(_OWORD *)(a1 + (v9 | 0x780)) = a4[8];
        *(_OWORD *)(a1 + (v9 | 0x790)) = a4[9];
        *(_OWORD *)(a1 + (v9 | 0x7A0)) = a4[10];
        *(_OWORD *)(a1 + (v9 | 0x7B0)) = a4[11];
        *(_OWORD *)(a1 + (v9 | 0x7C0)) = a4[12];
        *(_OWORD *)(a1 + (v9 | 0x7D0)) = a4[13];
        *(_OWORD *)(a1 + (v9 | 0x7E0)) = a4[14];
        *(_OWORD *)(a1 + ((v7 << 11) | 0x7F0)) = a4[15];
        goto LABEL_3;
      }
    }
    if ( a1 + v10 + 2048 <= (unsigned __int64)a4 )
      goto LABEL_2;
    v25 = -64LL;
    do
    {
      *(_DWORD *)(v8 + 4 * v25 + 2048) = *((_DWORD *)a4 + v25 + 64);
      ++v25;
    }
    while ( v25 );
LABEL_3:
    ++v7;
    v8 += 2048LL;
  }
  while ( v7 != 8 );
  v26 = a3 + 18432;
  v27 = a2 - 1280;
  v28 = a2 - 2304;
  v29 = 0LL;
  do
  {
    v96 = v29;
    v103 = v29 - 1;
    v98 = v28;
    v97 = v27;
    v99 = v26;
    v82 = v26;
    result = 0LL;
    do
    {
      v100 = result;
      v31 = result - 1;
      v102 = v28;
      v83 = v28;
      v101 = v27;
      v32 = 0LL;
      do
      {
        v84 = v32;
        if ( (unsigned __int64)(v32 + v103) <= 7 )
        {
          v33 = 8 * v32;
          v34 = 0LL;
          while ( (__int64)(v34 + v31) < 3 )
          {
            if ( (__int64)(v34 + v31) < 0 )
            {
              v35 = 1LL;
            }
            else
            {
              v36 = (v34 + v33) << 6;
              v37 = v27 + (v34 << 8);
              v38 = 0;
              v39 = v82;
              v40 = 0LL;
              do
              {
                v95 = 0LL;
                v41 = -256LL;
                v94 = 0LL;
                v93 = 0LL;
                v92 = 0LL;
                v91 = 0LL;
                v90 = 0LL;
                v89 = 0LL;
                v88 = 0LL;
                v87 = 0LL;
                v86 = 0LL;
                v85 = 0LL;
                v42 = 0LL;
                v43 = 0LL;
                v44 = 0LL;
                v45 = 0LL;
                v46 = 0LL;
                v47 = 0LL;
                v48 = 0LL;
                v49 = 0LL;
                v50 = 0LL;
                do
                {
                  v51 = _mm_shuffle_ps(
                          (__m128)*(unsigned int *)(v37 + v41 - 768),
                          (__m128)*(unsigned int *)(v37 + v41 - 768),
                          0);
                  v52 = _mm_shuffle_ps(
                          (__m128)*(unsigned int *)(v37 + v41 - 512),
                          (__m128)*(unsigned int *)(v37 + v41 - 512),
                          0);
                  v53 = *(__m128 *)(v39 + 8 * v41 - 0x4000);
                  v54 = *(__m128 *)(v39 + 8 * v41 - 16368);
                  v49 = _mm_add_ps(v49, _mm_mul_ps(v51, v53));
                  v50 = _mm_add_ps(v50, _mm_mul_ps(v51, v54));
                  v55 = *(__m128 *)(v39 + 8 * v41 + 2048);
                  v47 = _mm_add_ps(v47, _mm_mul_ps(v51, v55));
                  v56 = *(__m128 *)(v39 + 8 * v41 + 2064);
                  v48 = _mm_add_ps(v48, _mm_mul_ps(v51, v56));
                  v45 = _mm_add_ps(v45, _mm_mul_ps(v52, v53));
                  v46 = _mm_add_ps(v46, _mm_mul_ps(v52, v54));
                  v43 = _mm_add_ps(v43, _mm_mul_ps(v52, v55));
                  v57 = _mm_shuffle_ps(
                          (__m128)*(unsigned int *)(v37 + v41 - 256),
                          (__m128)*(unsigned int *)(v37 + v41 - 256),
                          0);
                  v44 = _mm_add_ps(v44, _mm_mul_ps(v52, v56));
                  v85 = _mm_add_ps(v85, _mm_mul_ps(v57, v53));
                  v42 = _mm_add_ps(v42, _mm_mul_ps(v57, v54));
                  v87 = _mm_add_ps(v87, _mm_mul_ps(v57, v55));
                  v58 = _mm_shuffle_ps((__m128)*(unsigned int *)(v37 + v41), (__m128)*(unsigned int *)(v37 + v41), 0);
                  v86 = _mm_add_ps(v86, _mm_mul_ps(v57, v56));
                  v89 = _mm_add_ps(v89, _mm_mul_ps(v58, v53));
                  v88 = _mm_add_ps(v88, _mm_mul_ps(v58, v54));
                  v91 = _mm_add_ps(v91, _mm_mul_ps(v58, v55));
                  v90 = _mm_add_ps(v90, _mm_mul_ps(v58, v56));
                  v59 = _mm_shuffle_ps(
                          (__m128)*(unsigned int *)(v37 + v41 + 256),
                          (__m128)*(unsigned int *)(v37 + v41 + 256),
                          0);
                  v93 = _mm_add_ps(v93, _mm_mul_ps(v53, v59));
                  v92 = _mm_add_ps(v92, _mm_mul_ps(v54, v59));
                  v95 = _mm_add_ps(v95, _mm_mul_ps(v55, v59));
                  v94 = _mm_add_ps(v94, _mm_mul_ps(v59, v56));
                  v41 += 4LL;
                }
                while ( v41 );
                v60 = v40 + v36;
                *(__m128 *)(a1 + 4 * v60 + 16) = _mm_add_ps(v50, *(__m128 *)(a1 + 4 * (v40 + v36) + 16));
                *(__m128 *)(a1 + 4 * v60) = _mm_add_ps(v49, *(__m128 *)(a1 + 4 * (v40 + v36)));
                v61 = (4 * (v40 + v36)) | 0x20;
                *(__m128 *)(a1 + v61) = _mm_add_ps(v47, *(__m128 *)(a1 + v61));
                *(__m128 *)(a1 + v61 + 16) = _mm_add_ps(v48, *(__m128 *)(a1 + v61 + 16));
                *(__m128 *)(a1 + 4 * v60 + 272) = _mm_add_ps(v46, *(__m128 *)(a1 + 4 * (v40 + v36) + 272));
                *(__m128 *)(a1 + 4 * v60 + 256) = _mm_add_ps(v45, *(__m128 *)(a1 + 4 * (v40 + v36) + 256));
                v62 = (4 * (v40 + v36) + 256) | 0x20;
                *(__m128 *)(a1 + v62) = _mm_add_ps(v43, *(__m128 *)(a1 + v62));
                *(__m128 *)(a1 + v62 + 16) = _mm_add_ps(v44, *(__m128 *)(a1 + v62 + 16));
                *(__m128 *)(a1 + 4 * v60 + 528) = _mm_add_ps(v42, *(__m128 *)(a1 + 4 * (v40 + v36) + 528));
                *(__m128 *)(a1 + 4 * v60 + 512) = _mm_add_ps(v85, *(__m128 *)(a1 + 4 * (v40 + v36) + 512));
                v63 = (4 * (v40 + v36) + 512) | 0x20;
                *(__m128 *)(a1 + v63) = _mm_add_ps(v87, *(__m128 *)(a1 + v63));
                *(__m128 *)(a1 + v63 + 16) = _mm_add_ps(v86, *(__m128 *)(a1 + v63 + 16));
                *(__m128 *)(a1 + 4 * v60 + 784) = _mm_add_ps(v88, *(__m128 *)(a1 + 4 * (v40 + v36) + 784));
                *(__m128 *)(a1 + 4 * v60 + 768) = _mm_add_ps(v89, *(__m128 *)(a1 + 4 * (v40 + v36) + 768));
                v64 = (4 * (v40 + v36) + 768) | 0x20;
                *(__m128 *)(a1 + v64) = _mm_add_ps(v91, *(__m128 *)(a1 + v64));
                *(__m128 *)(a1 + v64 + 16) = _mm_add_ps(v90, *(__m128 *)(a1 + v64 + 16));
                *(__m128 *)(a1 + 4 * v60 + 1040) = _mm_add_ps(v92, *(__m128 *)(a1 + 4 * (v40 + v36) + 1040));
                *(__m128 *)(a1 + 4 * v60 + 1024) = _mm_add_ps(v93, *(__m128 *)(a1 + 4 * (v40 + v36) + 1024));
                v65 = (4 * (v40 + v36) + 1024) | 0x20;
                *(__m128 *)(a1 + v65 + 16) = _mm_add_ps(v94, *(__m128 *)(a1 + v65 + 16));
                *(__m128 *)(a1 + v65) = _mm_add_ps(v95, *(__m128 *)(a1 + v65));
                v35 = 5LL;
                if ( v38 > 2 )
                  break;
                ++v38;
                v39 += 36864LL;
                v66 = v40 < 0x30;
                v40 += 16LL;
              }
              while ( v66 );
            }
            v34 += v35;
            if ( v34 >= 8 )
              goto LABEL_56;
          }
          v67 = v83 + (v34 << 8);
          do
          {
            if ( v34 + v31 <= 7 )
            {
              v68 = (v34 + v33) << 6;
              v69 = 0;
              v70 = v82;
              v71 = 0LL;
              do
              {
                v72 = 0LL;
                v73 = -256LL;
                v74 = 0LL;
                v75 = 0LL;
                v76 = 0LL;
                do
                {
                  v77 = _mm_shuffle_ps(
                          (__m128)*(unsigned int *)(v67 + v73 + 256),
                          (__m128)*(unsigned int *)(v67 + v73 + 256),
                          0);
                  v75 = _mm_add_ps(v75, _mm_mul_ps(*(__m128 *)(v70 + 8 * v73 - 0x4000), v77));
                  v76 = _mm_add_ps(v76, _mm_mul_ps(*(__m128 *)(v70 + 8 * v73 - 16368), v77));
                  v72 = _mm_add_ps(v72, _mm_mul_ps(*(__m128 *)(v70 + 8 * v73 + 2048), v77));
                  v74 = _mm_add_ps(v74, _mm_mul_ps(v77, *(__m128 *)(v70 + 8 * v73 + 2064)));
                  v73 += 4LL;
                }
                while ( v73 );
                v78 = v71 + v68;
                v79 = _mm_add_ps(v75, *(__m128 *)(a1 + 4 * (v71 + v68)));
                *(__m128 *)(a1 + 4 * v78 + 16) = _mm_add_ps(v76, *(__m128 *)(a1 + 4 * (v71 + v68) + 16));
                *(__m128 *)(a1 + 4 * v78) = v79;
                v80 = (4 * (v71 + v68)) | 0x20;
                v81 = _mm_add_ps(v74, *(__m128 *)(a1 + v80 + 16));
                *(__m128 *)(a1 + v80) = _mm_add_ps(v72, *(__m128 *)(a1 + v80));
                *(__m128 *)(a1 + v80 + 16) = v81;
                if ( v69 > 2 )
                  break;
                ++v69;
                v70 += 36864LL;
                v66 = v71 < 0x30;
                v71 += 16LL;
              }
              while ( v66 );
            }
            v67 += 256LL;
            v66 = v34++ < 7;
          }
          while ( v66 );
        }
LABEL_56:
        v32 = v84 + 1;
        v27 += 2048LL;
        v83 += 2048LL;
      }
      while ( v84 != 7 );
      result = v100 + 1;
      v82 += 2048LL;
      v27 = v101 + 256;
      v28 = v102 + 256;
    }
    while ( v100 != 2 );
    v29 = v96 + 1;
    v26 = v99 + 6144;
    v27 = v97 + 2048;
    v28 = v98 + 2048;
  }
  while ( v96 != 2 );
  return result;
}
